### ISSUE TITLE
Fetch information from fuzzwork

### ISSUE THREAD

**Issue by DDSNA** [DDSNA/DND-Learn-SQL-and-Python#2]
Goal: Grab info from fuzzwork's api jsons 
Explained: Grab info about EVE's trade nodes and items traded and import the data into a db to use in further calculations/operations

https://market.fuzzwork.co.uk/aggregates/?region=30000142&types=626

**Comment by e-sek** [comment]
https://market.fuzzwork.co.uk/aggregates/?region=30000142&types=2268,2305,2267,2288,2287,2307,2272,2309,2073,2310,2270,2306,2286,2311,2308,2393,2396,3779,2401,2390,2397,2392,3683,2389,2399,2395,2398,9828,2400,3645,2329,3828,9836,9832,44,3693,15317,3725,3689,2327,9842,2463,2317,2321,3695,9830,3697,9838,2312,3691,2319,9840,3775,2328,2358,2345,2344,2367,17392,2348,9834,2366,2361,17898,2360,2354,2352,9846,9848,2351,2349,2346,12836,17136,28974,2867,2868,2869,2870,2871,2872,2875,2876

**Comment by DDSNA** [comment]
Question: do you think it'd be better to have a local-copy of the json downloaded by the scripts automatically each time when run, then deleted or should we have a perpetually updated single file?

**Comment by DDSNA** [comment]
> 
> 
> https://market.fuzzwork.co.uk/aggregates/?region=30000142&types=2268,2305,2267,2288,2287,2307,2272,2309,2073,2310,2270,2306,2286,2311,2308,2393,2396,3779,2401,2390,2397,2392,3683,2389,2399,2395,2398,9828,2400,3645,2329,3828,9836,9832,44,3693,15317,3725,3689,2327,9842,2463,2317,2321,3695,9830,3697,9838,2312,3691,2319,9840,3775,2328,2358,2345,2344,2367,17392,2348,9834,2366,2361,17898,2360,2354,2352,9846,9848,2351,2349,2346,12836,17136,28974,2867,2868,2869,2870,2871,2872,2875,2876

I will also need some help with understanding what those values and ids mean. placeholders or pointer-words will do

**Comment by DDSNA** [comment]
![image](https://user-images.githubusercontent.com/79444147/120931972-92b00700-c6fc-11eb-846a-7827e53484ee.png)

_

> In region 30000142, i.e. ID for Jita
> item ID 2268, i.e. Aqueous liquids (i have a local table)
> has values for buy and sell
> the fuzz guy said this is pre-calculated so these are, somehow, the already useful values
> the buy orderse are kinda dogshit so in the case of aqueous I'd mostly be looking for min, max, median, volume to get an idea for how much is moved and how much I could sell for a given price
> and the sell order count to get an idea for competition for selling
> stddev, idk what that is
> percentile, I'm actually curious about how to read that
if you were to buy low and sell high, the percentile would let you see what the best 5% of the deals would look like
you get one good margin from the average numbers
and you get another good margin from the most extreme numbers that are moved at a far lower volume
so you get one margin for reliable trading and another for unreliable trading, maybe for something that takes longer to sell or could risk fucking with the regional market as a whole if done on in too large quantities


_

**Comment by DDSNA** [comment]
@e-sek  ping

**Comment by DDSNA** [comment]
@e-sek  ping, need legend for the categories and numbers in there

**Comment by e-sek** [comment]
**Weighted average**: Average price of a commodity, I believe based on filled orders
**Max**: Highest filled order value
**Min**: Lowest filled order value

(with a price range between 5.99 and 8.99, with the average price being 8.2 across 42.8 million units of Item 2268, I think you get the picture)

**stddev**: standard deviation. I think you know this one better than I do.
**median**: self-explanatory
**volume**: amount of items moved on a single day
**orderCount**: defined as "upper bound on the number of participants". Ignore for now.
**percentile**: average price of the top 5% of the total moved volume. Basically an average of the best deals.

**Comment by DDSNA** [comment]
Neat. Good job!

Do we have a table for the numbers like 2268 and regions in the screenshot above?

**Comment by DDSNA** [comment]
Closed with the previous issue #14
